apiVersion: apps/v1
kind: Deployment
metadata:
  name: happy-user-svc
  labels:
    app: happy-user-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: happy-user-svc
  template:
    metadata:
      labels:
        app: happy-user-svc
    spec:
      containers:
        - name: happy-user-svc
          image: syahdaromstudenttelu/happy-user-svc
          ports:
            - containerPort: 55000
          env:
            - name: APP_ENV
              value: 'prod'
            - name: DB_DRIVER
              value: 'mysql'
            - name: DB_SOURCE
              value: 'root:DdSmIMLTRZ@tcp(mysql.monitoring.svc.cluster.local:3306)/happy_mysql_db?parseTime=true'
            - name: SERVER_ADDR
              value: ':55000'
          resources:
            limits:
              cpu: 50m
              memory: 75Mi
            requests:
              cpu: 20m
              memory: 25Mi
