apiVersion: v1
kind: Service
metadata:
  name: happy-feedback-svc
spec:
  selector:
    app: happy-feedback-svc
  ports:
    - protocol: TCP
      port: 55000
      targetPort: 55000
  type: ClusterIP
